version: '1.1'

services:
  node:
    container_name: reja
    restart: always
    image: makhmud01/reja-image
    ports: 
      - 3006:3006
    volumes:
      - .:/usr/src/app/
    working_dir: /usr/src/app

    networks:
      - reja_network

    command: bash -c "npm install && npm run dev"

networks:
  reja_network:
    driver: bridge